import canopy

PatternInitializing = "CTP-eyJpZCI6ImRkMWVjY2MwLTE3ODYtNDhhYS05ZWE3LWNmMzAwODIwMTFhNCIsInZlcnNpb24iOjMsIm5hbWUiOiJXSWZpIERpc2Nvbm5lY3RlZCIsInBhbGV0dGVzIjp7IlBhbGV0dGUxIjpbWzAsWzEsMCwwXV0sWzAuOTksWzAsMCwwXV1dfSwicGFyYW1zIjp7IkNvbG9yIjoxfSwibGF5ZXJzIjpbeyJlZmZlY3QiOiJjaGFzZXIiLCJvcGFjaXR5IjoxLCJibGVuZCI6Im5vcm1hbCIsInBhbGV0dGUiOiJQYWxldHRlMSIsImlucHV0cyI6eyJvZmZzZXQiOnsidHlwZSI6InNpbiIsImlucHV0cyI6eyJ2YWx1ZSI6MC40OCwibWluIjowLCJtYXgiOjF9fSwic2l6ZSI6MC4zMX19XX0"
PatternRainbow = "CTP-eyJpZCI6IjAzNWVlN2NjLWZiM2MtNDI0Ni1hOTM1LTdjNGQ3ZDYyMzEyMyIsInZlcnNpb24iOjEsIm5hbWUiOiJOZXcgUGF0dGVybiIsInBhbGV0dGVzIjp7IlBhbGV0dGUxIjpbWzAsWzEsMCwwXV0sWzAuMTksWzAuOTY0NzA1ODgyMzUyOTQxMiwxLDBdXSxbMC4zNixbMC4wNjI3NDUwOTgwMzkyMTU2OSwxLDAuMDUwOTgwMzkyMTU2ODYyNzQ0XV0sWzAuNTEsWzAsMSwwLjg3MDU4ODIzNTI5NDExNzddXSxbMC42NyxbMCwwLjA5MDE5NjA3ODQzMTM3MjU1LDFdXSxbMC44MixbMC40OCwwLjAxLDAuNDJdXSxbMC45OSxbMSwwLDBdXV19LCJwYXJhbXMiOnsicHJvZ3Jlc3MiOjB9LCJsYXllcnMiOlt7ImVmZmVjdCI6ImdyYWRpZW50Iiwib3BhY2l0eSI6InByb2dyZXNzIiwiYmxlbmQiOiJub3JtYWwiLCJwYWxldHRlIjoiUGFsZXR0ZTEiLCJpbnB1dHMiOnsib2Zmc2V0Ijp7InR5cGUiOiJyc2F3IiwiaW5wdXRzIjp7InZhbHVlIjowLjQxLCJtaW4iOjAsIm1heCI6MX19LCJzaXplIjowLjUsInJvdGF0aW9uIjowfX1dfQ"
ArtifactWaitingPattern = "CTP-eyJpZCI6IjY1YmNiOTNmLTE5MTktNGFiNi1iZWQ4LWVmOGQyZmRjN2Q1OSIsInZlcnNpb24iOjIsIm5hbWUiOiJBcnRpZmFjdCAtIFJlYWR5IiwicGFsZXR0ZXMiOnsiQ29sb3JzIjpbWzAsWzEsMCwwXV0sWzAuMTUsWzEsMC43MTc2NDcwNTg4MjM1Mjk0LDBdXSxbMC4yOSxbMC45MDE5NjA3ODQzMTM3MjU1LDEsMF1dLFswLjQ0LFswLjI4MjM1Mjk0MTE3NjQ3MDYsMSwwXV0sWzAuNTksWzAsMC44NjY2NjY2NjY2NjY2NjY3LDFdXSxbMC43MyxbMC4wNjY2NjY2NjY2NjY2NjY2NywwLDFdXSxbMC44NixbMC41MTc2NDcwNTg4MjM1Mjk1LDAsMV1dLFswLjk4LFsxLDAsMC43NDkwMTk2MDc4NDMxMzczXV1dLCJPdmVybGF5IjpbWzAsWzAsMCwwXV0sWzEsWzAuNTY4NjI3NDUwOTgwMzkyMSwwLjU2ODYyNzQ1MDk4MDM5MjEsMC41Njg2Mjc0NTA5ODAzOTIxXV1dLCJDaGFzZXIgT3ZlcmxheSI6W1swLFsxLDEsMV1dLFsxLFsxLDEsMV1dXX0sInBhcmFtcyI6eyJDb2xvciI6MC41OSwiVGltZXIiOjF9LCJsYXllcnMiOlt7ImVmZmVjdCI6InNvbGlkIiwib3BhY2l0eSI6eyJ0eXBlIjoic2luIiwiaW5wdXRzIjp7InZhbHVlIjowLjU3LCJtaW4iOjAsIm1heCI6MC44Mn19LCJibGVuZCI6Im5vcm1hbCIsInBhbGV0dGUiOiJDb2xvcnMiLCJpbnB1dHMiOnsib2Zmc2V0IjoiQ29sb3IifX0seyJlZmZlY3QiOiJzcGFya2xlcyIsIm9wYWNpdHkiOjAuNDcsImJsZW5kIjoib3ZlcmxheSIsInBhbGV0dGUiOiJPdmVybGF5IiwiaW5wdXRzIjp7ImRlbnNpdHkiOnsidHlwZSI6InNpbiIsImlucHV0cyI6eyJ2YWx1ZSI6MC4zMywibWluIjowLjE1LCJtYXgiOjAuNjl9fSwib2Zmc2V0Ijp7InR5cGUiOiJzaW4iLCJpbnB1dHMiOnsidmFsdWUiOjAuMzIsIm1pbiI6MCwibWF4IjoxfX19fSx7ImVmZmVjdCI6InNwYXJrbGVzIiwib3BhY2l0eSI6eyJ0eXBlIjoic2luIiwiaW5wdXRzIjp7InZhbHVlIjowLjU1LCJtaW4iOjAsIm1heCI6MC42N319LCJibGVuZCI6Im5vcm1hbC1ub25ibGFjayIsInBhbGV0dGUiOiJPdmVybGF5IiwiaW5wdXRzIjp7ImRlbnNpdHkiOjAuMTksIm9mZnNldCI6eyJ0eXBlIjoic2luIiwiaW5wdXRzIjp7InZhbHVlIjowLjI0LCJtaW4iOjAsIm1heCI6MX19fX0seyJlZmZlY3QiOiJjaGFzZXIiLCJvcGFjaXR5IjoxLCJibGVuZCI6Im11bHRpcGx5IiwicGFsZXR0ZSI6IkNoYXNlciBPdmVybGF5IiwiaW5wdXRzIjp7Im9mZnNldCI6IlRpbWVyIiwic2l6ZSI6MX19XX0"
ArtifactConnectedPattern = "CTP-eyJpZCI6IjFhMjQ5MmUwLTY2ZGMtNGJmMi04ODY1LTYxNTIwMzNlZTk2ZSIsInZlcnNpb24iOjIsIm5hbWUiOiJBcnRpZmFjdCAtIENvbm5lY3RlZCBDb2xvcnMiLCJwYWxldHRlcyI6eyJDb2xvcnMiOltbMCxbMSwwLDBdXSxbMC4xNSxbMSwwLjcyLDBdXSxbMC4yNyxbMC45LDEsMF1dLFswLjQ0LFswLjI4LDEsMF1dLFswLjU5LFswLDAuODcsMV1dLFswLjczLFswLjA3LDAsMV1dLFswLjg2LFswLjUyLDAsMV1dLFsxLFsxLDAsMC43NV1dXSwiQnJpZ2h0bmVzcyI6W1swLjE0LFswLDAsMF1dLFswLjI1LFsxLDEsMV1dLFswLjM5LFswLDAsMF1dLFswLjU1LFswLDAsMF1dLFswLjY1LFsxLDEsMV1dLFswLjc1LFswLDAsMF1dXX0sInBhcmFtcyI6eyJDb2xvciI6MH0sImxheWVycyI6W3siZWZmZWN0Ijoic29saWQiLCJvcGFjaXR5IjoxLCJibGVuZCI6Im5vcm1hbCIsInBhbGV0dGUiOiJDb2xvcnMiLCJpbnB1dHMiOnsib2Zmc2V0IjoiQ29sb3IifX0seyJlZmZlY3QiOiJjaGFzZXIiLCJvcGFjaXR5IjowLjYsImJsZW5kIjoibXVsdGlwbHkiLCJwYWxldHRlIjoiQnJpZ2h0bmVzcyIsImlucHV0cyI6eyJvZmZzZXQiOnsidHlwZSI6InNpbiIsImlucHV0cyI6eyJ2YWx1ZSI6MC41LCJtaW4iOjAuMTMsIm1heCI6MX19LCJzaXplIjowLjQ1fX0seyJlZmZlY3QiOiJzcGFya2xlcyIsIm9wYWNpdHkiOjAuNywiYmxlbmQiOiJvdmVybGF5IiwicGFsZXR0ZSI6IkJyaWdodG5lc3MiLCJpbnB1dHMiOnsiZGVuc2l0eSI6MC42MSwib2Zmc2V0Ijp7InR5cGUiOiJ0cmlhbmdsZSIsImlucHV0cyI6eyJ2YWx1ZSI6MC4yOCwibWluIjowLCJtYXgiOjF9fX19XX0"
ArtifactIncorrectPattern = "CTP-eyJpZCI6IjdkYjZiOGM3LTJkZjYtNDAzNC1iZjA1LTk3MTAxZDI3N2FhZiIsInZlcnNpb24iOjEzLCJuYW1lIjoiQXJ0aWZhY3QgSW5jb3JyZWN0IiwicGFsZXR0ZXMiOnsiUGFsZXR0ZTEiOltbMC40MSxbMSwwLDBdXV19LCJwYXJhbXMiOnsiQ29sb3IiOjF9LCJsYXllcnMiOlt7ImVmZmVjdCI6ImNoYXNlciIsIm9wYWNpdHkiOnsidHlwZSI6InNxdWFyZSIsImlucHV0cyI6eyJ2YWx1ZSI6MC42OSwibWluIjowLCJtYXgiOjF9fSwiYmxlbmQiOiJub3JtYWwiLCJwYWxldHRlIjoiUGFsZXR0ZTEiLCJpbnB1dHMiOnsib2Zmc2V0IjoxLCJzaXplIjoxfX1dfQ"
ArtifactOffPattern = "CTP-eyJpZCI6Ijk2NTRmMDA4LWNlMjUtNDAwNS04MWE0LTc0NzY5MjJlOWNmZSIsInZlcnNpb24iOjYsIm5hbWUiOiJBcnRpZmFjdCAtIE9mZiIsInBhbGV0dGVzIjp7IkNvbG9ycyI6W1swLjAyLFswLjYxOTYwNzg0MzEzNzI1NDksMC4zODgyMzUyOTQxMTc2NDcwNywwLjA4NjI3NDUwOTgwMzkyMTU3XV0sWzAuMTQsWzAuNzQxMTc2NDcwNTg4MjM1MywwLjc0OTAxOTYwNzg0MzEzNzMsMC4zMDU4ODIzNTI5NDExNzY1XV0sWzAuMjksWzAuNTA1ODgyMzUyOTQxMTc2NCwwLjgxOTYwNzg0MzEzNzI1NDksMC4yMTE3NjQ3MDU4ODIzNTI5NF1dLFswLjQzLFswLjMyOTQxMTc2NDcwNTg4MjM1LDAuODcwNTg4MjM1Mjk0MTE3NywwLjEyMTU2ODYyNzQ1MDk4MDM5XV0sWzAuNTksWzAuMDYyNzQ1MDk4MDM5MjE1NjksMC44NzA1ODgyMzUyOTQxMTc3LDAuNjU0OTAxOTYwNzg0MzEzN11dLFswLjc0LFswLjIxNTY4NjI3NDUwOTgwMzkzLDAuNTI5NDExNzY0NzA1ODgyNCwwLjcwMTk2MDc4NDMxMzcyNTRdXSxbMC44NyxbMC4wMTk2MDc4NDMxMzcyNTQ5LDAuNTI5NDExNzY0NzA1ODgyNCwwLjI0MzEzNzI1NDkwMTk2MDc4XV0sWzAuOTksWzAuNTEzNzI1NDkwMTk2MDc4NCwwLjY1ODgyMzUyOTQxMTc2NDcsMC4xNDUwOTgwMzkyMTU2ODYzXV1dLCJCcmlnaHRuZXNzIjpbWzAuMTQsWzAsMCwwXV0sWzAuMjUsWzEsMSwxXV0sWzAuMzksWzAsMCwwXV0sWzAuNTUsWzAsMCwwXV0sWzAuNjUsWzEsMSwxXV0sWzAuNzUsWzAsMCwwXV1dfSwicGFyYW1zIjp7IkNvbG9yIjp7InR5cGUiOiJzaW4iLCJpbnB1dHMiOnsidmFsdWUiOjAuNDEsIm1pbiI6MCwibWF4IjoxfX19LCJsYXllcnMiOlt7ImVmZmVjdCI6InNvbGlkIiwib3BhY2l0eSI6MSwiYmxlbmQiOiJub3JtYWwiLCJwYWxldHRlIjoiQ29sb3JzIiwiaW5wdXRzIjp7Im9mZnNldCI6IkNvbG9yIn19LHsiZWZmZWN0Ijoic3BhcmtsZXMiLCJvcGFjaXR5IjoxLCJibGVuZCI6Im11bHRpcGx5IiwicGFsZXR0ZSI6IkJyaWdodG5lc3MiLCJpbnB1dHMiOnsiZGVuc2l0eSI6MC4yNCwib2Zmc2V0Ijp7InR5cGUiOiJzaW4iLCJpbnB1dHMiOnsidmFsdWUiOjAuMTQsIm1pbiI6MCwibWF4IjoxfX19fV19"

initializing_pattern = canopy.Pattern(PatternInitializing)
connected_pattern = canopy.Pattern(ArtifactConnectedPattern)
off_pattern = canopy.Pattern(ArtifactOffPattern)
incorrect_pattern = canopy.Pattern(ArtifactIncorrectPattern)
waiting_pattern = canopy.Pattern(ArtifactWaitingPattern)
writing_pattern = canopy.Pattern(PatternRainbow)

MODE_INITIALIZING = 0
MODE_OFF = 1
MODE_WAITING = 2
MODE_CONNECTED = 3
MODE_INVALID = 4
MODE_WRITING = 5


class RingLight(object):
    current_mode = MODE_INITIALIZING

    def __init__(self):
        self.segment = canopy.Segment(0, 0, 16)
        self.params = canopy.Params()

    def _update_light_pattern(self):
        if self.current_mode == MODE_INITIALIZING:
            self.light_pattern = initializing_pattern
        elif self.current_mode == MODE_INVALID:
            self.light_pattern = incorrect_pattern
        elif self.current_mode == MODE_CONNECTED:
            self.light_pattern = connected_pattern
        elif self.current_mode == MODE_WAITING:
            self.light_pattern = waiting_pattern
        elif self.current_mode == MODE_WRITING:
            self.light_pattern = writing_pattern
        elif self.current_mode == MODE_OFF:
            self.light_pattern = off_pattern
        print("Updated light pattern to: ", self.light_pattern)

    def set_mode(self, mode):
        self.current_mode = mode
        self._update_light_pattern()

    def draw(self):
        canopy.draw(
            self.segment,
            self.light_pattern,
            alpha=float(0.8),
            params=self.params,
        )
